[package]
name = "bevy_boilerplate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.1"
bevy_prototype_debug_lines = "0.9.0"
lerp = "0.4.0"
rand = "0.8.5"
